#!/bin/bash

set -e

RELEASES=build/repos/releases/com
ASSEMBLE=$(mktemp -d)
cp -R $RELEASES $ASSEMBLE

# Enter temp dir
pushd $ASSEMBLE

rm com/inngest/inngest-spring-boot-adapter/maven-*
zip -r bundle.zip com

popd

cp $ASSEMBLE/bundle.zip .

rm -rf $ASSEMBLE
